using TenderingSystem.Domain.Enums;

namespace TenderingSystem.Domain.Entities;

public class AiSearchLog
{
    public Guid Id { get; set; } = Guid.NewGuid();
    
    public Guid TenderId { get; set; }
    public Tender Tender { get; set; } = null!;

    public string SearchKeywords { get; set; } = string.Empty; // Keywords generated by Gemini LLM
    public DateTime StartedAt { get; set; } = DateTime.UtcNow;
    public DateTime? CompletedAt { get; set; }
    public AiSearchStatus Status { get; set; } = AiSearchStatus.Pending;
    public int SuppliersFoundCount { get; set; } = 0;
    
    // Logs about the execution (e.g. Scraper errors, LLM token usage)
    public string ExecutionNotes { get; set; } = string.Empty; 
}
